Convert str of unicode chars to str of bytes
This fixes:
  ...
  File "memory_profiler.py", line 31, in _get_memory
    stdout=subprocess.PIPE).communicate()[0].split('\n')
TypeError: Type str doesn't support the buffer API